# docker-compose -f docker-compose.yml up -d
version: "3.0"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  node: # node 服务
        build:  # Dockerfile 的目录，用于构建镜像
          context: ./
          dockerfile: serve/Dockerfile
        container_name: node-server # 容器名称
        ports: # 暴露的端口
            - "3000:3000"
        restart: always # 自动重启
        environment: # 设置环境变量
            - NODE_ENV=production
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb
        command: npm run serve # 覆盖容器启动后默认执行的命令


networks:
  default:
    name: mongodb_network
